-- 002_tables.sql
-- Физическая модель по ТЗ: основные, лабораторные, НСИ, результаты, staging.
-- Справочники объектов/лабораторий/показателей наполняются на этапе 2.

CREATE TABLE eco.ref_media_types (
    media_code  text        PRIMARY KEY,
    name_ru     text        NOT NULL,
    name_en     text        NOT NULL,
    sort_order  integer     NOT NULL DEFAULT 0
);

COMMENT ON TABLE eco.ref_media_types IS
  'Типы среды мониторинга: воздух, поверхностные/подземные воды, почва, растительность.';

INSERT INTO eco.ref_media_types (media_code, name_ru, name_en, sort_order) VALUES
    ('air',             'Атмосферный воздух',     'Ambient air',             1),
    ('surface_water',   'Поверхностные воды',     'Surface water',           2),
    ('groundwater',     'Подземные воды',         'Groundwater',             3),
    ('soil',            'Почва',                  'Soil',                    4),
    ('vegetation',      'Растительность',         'Vegetation',              5);

CREATE TABLE eco.ref_qc_codes (
    qc_code             char(1)     PRIMARY KEY,
    name_ru             text        NOT NULL,
    name_en             text        NOT NULL,
    include_in_latest   boolean     NOT NULL DEFAULT true
);

COMMENT ON TABLE eco.ref_qc_codes IS
  'Коды QA/QC результата: A/B/C/D/R. Записи D и R исключаются из vw_latest_results.';

INSERT INTO eco.ref_qc_codes (qc_code, name_ru, name_en, include_in_latest) VALUES
    ('A', 'Высшее качество / поверено',           'Highest quality',              true),
    ('B', 'Ограничения (в т.ч. < МДО)',           'Qualified / estimated',        true),
    ('C', 'Принято по умолчанию',                 'Default accepted',             true),
    ('D', 'Отклонено',                            'Rejected',                     false),
    ('R', 'На ручной разбор / повтор',            'Review / rerun',               false);

-- ---------------------------------------------------------------------------
-- Пространственные / объектные
-- ---------------------------------------------------------------------------

CREATE TABLE eco.sites (
    site_id     bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_code   text        NOT NULL,
    name_ru     text        NOT NULL,
    name_en     text,
    description text,
    region      text,
    is_active   boolean     NOT NULL DEFAULT true,
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_sites_code UNIQUE (site_code)
);

COMMENT ON TABLE eco.sites IS 'Производственные объекты (площадки) мониторинга.';

CREATE TABLE eco.monitoring_points (
    point_id    bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    point_code  text        NOT NULL,
    site_id     bigint      NOT NULL REFERENCES eco.sites (site_id),
    name_ru     text        NOT NULL,
    name_en     text,
    media_type  text        NOT NULL REFERENCES eco.ref_media_types (media_code),
    point_type  text,
    geom        geometry(Point, 4326),
    elevation_m numeric(10, 2),
    is_active   boolean     NOT NULL DEFAULT true,
    comments    text,
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_monitoring_points_code UNIQUE (point_code)
);

COMMENT ON TABLE eco.monitoring_points IS
  'Точки наблюдения. geom — WGS84 (EPSG:4326), совместимо с ArcGIS Enterprise.';
COMMENT ON COLUMN eco.monitoring_points.geom IS 'GEOMETRY(Point, 4326), долгота/широта.';
COMMENT ON COLUMN eco.monitoring_points.point_type IS
  'Классификация точки: скважина, граница СЗЗ, водоток и т.п.';

CREATE TABLE eco.point_aliases (
    alias_id        bigint  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    point_id        bigint  NOT NULL REFERENCES eco.monitoring_points (point_id) ON DELETE CASCADE,
    alias_norm      text    NOT NULL,
    source_system   text
);

COMMENT ON TABLE eco.point_aliases IS
  'Синонимы кодов точек (Т-1 / Т.№1 / скважина ФС-1) для сопоставления при ETL.';

-- ---------------------------------------------------------------------------
-- Лаборатории, события, пробы
-- ---------------------------------------------------------------------------

CREATE TABLE eco.laboratories (
    lab_id              bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lab_code            text        NOT NULL,
    name_ru             text        NOT NULL,
    name_en             text,
    accreditation_no    text,
    is_active           boolean     NOT NULL DEFAULT true,
    created_at          timestamptz NOT NULL DEFAULT now(),
    updated_at          timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_laboratories_code UNIQUE (lab_code)
);

COMMENT ON TABLE eco.laboratories IS 'Лаборатории — источники аналитических данных (ЛАБ1, ЛАБ2, ЛАБ3, …).';

CREATE TABLE eco.sampling_events (
    event_id        bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id         bigint      NOT NULL REFERENCES eco.sites (site_id),
    point_id        bigint      NOT NULL REFERENCES eco.monitoring_points (point_id),
    event_date      date        NOT NULL,
    event_datetime  timestamptz,
    media_type      text        NOT NULL REFERENCES eco.ref_media_types (media_code),
    sampled_by      text,
    comments        text,
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_sampling_events_point_date UNIQUE (point_id, event_date, media_type)
);

COMMENT ON TABLE eco.sampling_events IS
  'Событие отбора: объект + точка + дата (+ тип среды). Одна запись на совпадение по ТЗ 6.3.';

CREATE TABLE eco.samples (
    sample_id               bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id                bigint      NOT NULL REFERENCES eco.sampling_events (event_id),
    lab_id                  bigint      REFERENCES eco.laboratories (lab_id),
    sample_code             text,
    sample_type             text,
    collection_datetime     timestamptz,
    received_datetime       timestamptz,
    coc_number              text,
    comments                text,
    created_at              timestamptz NOT NULL DEFAULT now(),
    updated_at              timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE eco.samples IS
  'Проба: метаданные отбора, лаборатория, цепочка хранения (CoC).';
COMMENT ON COLUMN eco.samples.coc_number IS 'Номер акта цепочки хранения пробы (Chain of Custody).';
COMMENT ON COLUMN eco.samples.sample_type IS 'Тип пробы: разовая, составная, холостая и т.п.';

-- ---------------------------------------------------------------------------
-- Нормативно-справочные: показатели и ПДК
-- ---------------------------------------------------------------------------

CREATE TABLE eco.parameters (
    param_id        bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    param_code      text        NOT NULL,
    name_ru         text        NOT NULL,
    name_en         text,
    cas_rn          text,
    unit            text        NOT NULL,
    media_type      text        REFERENCES eco.ref_media_types (media_code),
    mdl_default     numeric(18, 8),
    group_name      text,
    sort_order      integer     NOT NULL DEFAULT 0,
    is_active       boolean     NOT NULL DEFAULT true,
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_parameters_code UNIQUE (param_code)
);

COMMENT ON TABLE eco.parameters IS
  'Реестр показателей (RU/EN), каноническая единица измерения и МДО по умолчанию.';
COMMENT ON COLUMN eco.parameters.mdl_default IS
  'Минимально определяемая концентрация (МДО / MDL) метода по умолчанию.';
COMMENT ON COLUMN eco.parameters.media_type IS
  'Основная среда показателя; NULL — применим к нескольким средам.';

CREATE TABLE eco.parameter_aliases (
    alias_id        bigint  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    param_id        bigint  NOT NULL REFERENCES eco.parameters (param_id) ON DELETE CASCADE,
    alias_norm      text    NOT NULL,
    source_system   text
);

COMMENT ON TABLE eco.parameter_aliases IS
  'Синонимы названий/кодов показателей лабораторий (ПЭК, ALAB, протоколы) для маппинга ETL.';

CREATE TABLE eco.guideline_standards (
    standard_id     bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    standard_code   text        NOT NULL,
    name_ru         text        NOT NULL,
    name_en         text,
    authority       text,
    media_type      text        REFERENCES eco.ref_media_types (media_code),
    is_active       boolean     NOT NULL DEFAULT true,
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_guideline_standards_code UNIQUE (standard_code)
);

COMMENT ON TABLE eco.guideline_standards IS
  'Нормативные документы / виды нормативов (ПДК м.р. воздуха, ПДК воды и т.д.).';

CREATE TABLE eco.guideline_values (
    gv_id           bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    standard_id     bigint      NOT NULL REFERENCES eco.guideline_standards (standard_id),
    param_id        bigint      NOT NULL REFERENCES eco.parameters (param_id),
    media_type      text        NOT NULL REFERENCES eco.ref_media_types (media_code),
    comparison_op   text        NOT NULL DEFAULT 'GT',
    limit_value     numeric(18, 8),
    limit_min       numeric(18, 8),
    limit_max       numeric(18, 8),
    unit            text,
    valid_from      date        NOT NULL DEFAULT DATE '1900-01-01',
    valid_to        date,
    comments        text,
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT ck_guideline_values_op CHECK (comparison_op IN ('GT', 'GTE', 'LT', 'LTE', 'RANGE')),
    CONSTRAINT ck_guideline_values_limit CHECK (
        (comparison_op IN ('GT', 'GTE', 'LT', 'LTE') AND limit_value IS NOT NULL)
        OR (comparison_op = 'RANGE' AND limit_min IS NOT NULL AND limit_max IS NOT NULL)
    ),
    CONSTRAINT ck_guideline_values_period CHECK (valid_to IS NULL OR valid_to >= valid_from),
    CONSTRAINT uq_guideline_values UNIQUE (standard_id, param_id, media_type, valid_from)
);

COMMENT ON TABLE eco.guideline_values IS
  'Численные нормативы (ПДК) показателя с периодом действия. «нет ПДК» = отсутствие строки.';
COMMENT ON COLUMN eco.guideline_values.comparison_op IS
  'GT/GTE — превышение верхней границы; LT/LTE — ниже нижней; RANGE — вне интервала (pH).';

-- ---------------------------------------------------------------------------
-- Результаты и превышения
-- ---------------------------------------------------------------------------

CREATE TABLE eco.results (
    result_id           bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sample_id           bigint      NOT NULL REFERENCES eco.samples (sample_id),
    param_id            bigint      NOT NULL REFERENCES eco.parameters (param_id),
    result_value        numeric(18, 8),
    less_than           boolean     NOT NULL DEFAULT false,
    unit                text,
    mdl                 numeric(18, 8),
    qc_code             char(1)     REFERENCES eco.ref_qc_codes (qc_code),
    lab_method          text,
    analysis_datetime   timestamptz,
    comments            text,
    created_at          timestamptz NOT NULL DEFAULT now(),
    updated_at          timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_results_sample_param UNIQUE (sample_id, param_id),
    CONSTRAINT ck_results_value CHECK (less_than OR result_value IS NOT NULL)
);

COMMENT ON TABLE eco.results IS
  'Лабораторные результаты. Пара (sample_id, param_id) уникальна; повторная загрузка обновляет запись.';
COMMENT ON COLUMN eco.results.less_than IS
  'TRUE, если исходное значение «ниже предела обнаружения» (<, ≤, не обн.). result_value тогда = МДО.';
COMMENT ON COLUMN eco.results.qc_code IS
  'Код QA/QC. NULL — не определён, подлежит ручной проверке. D и R скрываются во vw_latest_results.';

CREATE TABLE eco.result_exceedances (
    exceedance_id       bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    result_id           bigint      NOT NULL REFERENCES eco.results (result_id) ON DELETE CASCADE,
    gv_id               bigint      NOT NULL REFERENCES eco.guideline_values (gv_id),
    standard_id         bigint      NOT NULL REFERENCES eco.guideline_standards (standard_id),
    limit_value_applied numeric(18, 8) NOT NULL,
    ratio               numeric(18, 6) NOT NULL,
    exceedance_pct      numeric(18, 4) NOT NULL,
    detected_at         timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_result_exceedances UNIQUE (result_id, gv_id)
);

COMMENT ON TABLE eco.result_exceedances IS
  'Автоматически выявленные превышения нормативов. Повторный проход не создаёт дублей (unique result_id + gv_id).';
COMMENT ON COLUMN eco.result_exceedances.ratio IS 'Коэффициент превышения: result_value / limit_value.';
COMMENT ON COLUMN eco.result_exceedances.exceedance_pct IS
  'Процент превышения: (result_value − limit) / limit × 100.';

-- ---------------------------------------------------------------------------
-- Полевые измерения, уровни воды, вложения
-- ---------------------------------------------------------------------------

CREATE TABLE eco.field_measurements (
    measurement_id      bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    point_id            bigint      NOT NULL REFERENCES eco.monitoring_points (point_id),
    event_id            bigint      REFERENCES eco.sampling_events (event_id),
    param_id            bigint      NOT NULL REFERENCES eco.parameters (param_id),
    measured_datetime   timestamptz NOT NULL,
    result_value        numeric(18, 8) NOT NULL,
    unit                text,
    instrument          text,
    comments            text,
    created_at          timestamptz NOT NULL DEFAULT now(),
    updated_at          timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE eco.field_measurements IS
  'Полевые измерения (pH, температура, электропроводность, растворённый кислород и др.).';

CREATE TABLE eco.water_levels (
    level_id                    bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    point_id                    bigint      NOT NULL REFERENCES eco.monitoring_points (point_id),
    measured_datetime           timestamptz NOT NULL,
    depth_to_water_m            numeric(10, 3),
    water_elevation_m           numeric(10, 3),
    measuring_point_elevation_m numeric(10, 3),
    comments                    text,
    created_at                  timestamptz NOT NULL DEFAULT now(),
    updated_at                  timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_water_levels_point_time UNIQUE (point_id, measured_datetime),
    CONSTRAINT ck_water_levels_value CHECK (
        depth_to_water_m IS NOT NULL OR water_elevation_m IS NOT NULL
    )
);

COMMENT ON TABLE eco.water_levels IS 'Уровни подземных вод (глубина до зеркала и/или абсолютная отметка).';

CREATE TABLE eco.attachments (
    attachment_id   bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type     text        NOT NULL,
    entity_id       bigint      NOT NULL,
    file_name       text        NOT NULL,
    file_uri        text,
    mime_type       text,
    description     text,
    uploaded_at     timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT ck_attachments_entity CHECK (
        entity_type IN ('site', 'monitoring_point', 'sampling_event', 'sample', 'result', 'laboratory')
    )
);

COMMENT ON TABLE eco.attachments IS
  'Вложения (протоколы PDF и др.), связанные с записью по entity_type + entity_id.';

-- ---------------------------------------------------------------------------
-- Staging: сырой приём файлов лабораторий без преобразований
-- ---------------------------------------------------------------------------

CREATE TABLE eco.staging_lab_import (
    staging_id              bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_code              text        NOT NULL,
    source_file             text,
    source_sheet            text,
    row_no                  integer,
    lab_code                text,
    site_code               text,
    point_code              text,
    sample_code             text,
    media_type              text,
    param_code              text,
    param_name_raw          text,
    collection_date         date,
    collection_datetime     timestamptz,
    result_text             text,
    unit_raw                text,
    pdk_raw                 text,
    year_num                integer,
    quarter_num             integer,
    extra_json              jsonb,
    loaded_at               timestamptz NOT NULL DEFAULT now(),
    processed_at            timestamptz,
    process_error           text,
    CONSTRAINT ck_staging_quarter CHECK (quarter_num IS NULL OR quarter_num BETWEEN 1 AND 4)
);

COMMENT ON TABLE eco.staging_lab_import IS
  'Промежуточная таблица сырых строк лабораторных файлов. Без FK: сначала слепок, затем fn_process_staging_import.';
COMMENT ON COLUMN eco.staging_lab_import.batch_code IS 'Код партии загрузки (идемпотентный повтор по партии).';
COMMENT ON COLUMN eco.staging_lab_import.result_text IS 'Сырое значение ячейки (число, «<0.001», «не обн.», пусто).';
COMMENT ON COLUMN eco.staging_lab_import.process_error IS
  'Причина, по которой строка не загружена в results; processed_at IS NULL — можно повторить.';
COMMENT ON COLUMN eco.staging_lab_import.extra_json IS 'Поля источника, не попавшие в типизированные колонки.';

INSERT INTO eco.schema_migrations (version, description)
VALUES ('002', 'Таблицы, ограничения, справочники media/QC')
ON CONFLICT (version) DO NOTHING;
