-- 009_qaqc.sql
-- Журнал QA/QC: прогоны, замечания, выборочная сверка, причина кода QC.

ALTER TABLE eco.results
    ADD COLUMN IF NOT EXISTS qc_reason text;

COMMENT ON COLUMN eco.results.qc_reason IS
  'Почему присвоен qc_code. Заполняется прогоном QA/QC.';

CREATE TABLE IF NOT EXISTS eco.qa_rules (
    rule_code       text        PRIMARY KEY,
    qc_code         char(1)     REFERENCES eco.ref_qc_codes (qc_code),
    priority        integer     NOT NULL,
    description_ru  text        NOT NULL
);

INSERT INTO eco.qa_rules (rule_code, qc_code, priority, description_ru) VALUES
    ('protocol_mismatch', 'R', 10, 'Выборочная сверка с протоколом: значение не совпало'),
    ('protocol_match',    'A', 20, 'Значение совпало с протоколом PDF'),
    ('imputed_nondetect', 'R', 30, 'Пустая ячейка заменена на «не обн.» при загрузке — нужен ручной разбор'),
    ('unit_mismatch',     'R', 40, 'Единица результата отличается от справочника parameters.unit'),
    ('outlier_10x',       'R', 50, 'Значение больше применимого ПДК более чем в 10 раз'),
    ('below_mdl',         'B', 60, 'Ниже предела обнаружения (<, ≤, «не обн.» в источнике)'),
    ('default_accept',    'C', 70, 'Числовой результат без сработавших правил; код по умолчанию')
ON CONFLICT (rule_code) DO UPDATE
SET qc_code = EXCLUDED.qc_code,
    priority = EXCLUDED.priority,
    description_ru = EXCLUDED.description_ru;

CREATE TABLE IF NOT EXISTS eco.qa_runs (
    qa_run_id       bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rules_version   text        NOT NULL,
    started_at      timestamptz NOT NULL DEFAULT now(),
    finished_at     timestamptz,
    notes           text
);

CREATE TABLE IF NOT EXISTS eco.qa_findings (
    finding_id      bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    qa_run_id       bigint      NOT NULL REFERENCES eco.qa_runs (qa_run_id) ON DELETE CASCADE,
    severity        text        NOT NULL,
    check_code      text        NOT NULL,
    batch_code      text,
    message         text        NOT NULL,
    details         jsonb,
    CONSTRAINT ck_qa_findings_severity CHECK (severity IN ('info', 'warning', 'error'))
);

CREATE INDEX IF NOT EXISTS idx_qa_findings_run
    ON eco.qa_findings (qa_run_id, severity);

CREATE TABLE IF NOT EXISTS eco.qa_spot_checks (
    spot_id         bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    qa_run_id       bigint      NOT NULL REFERENCES eco.qa_runs (qa_run_id) ON DELETE CASCADE,
    result_id       bigint      REFERENCES eco.results (result_id) ON DELETE CASCADE,
    sample_kind     text        NOT NULL,
    protocol_file   text,
    protocol_page   text,
    protocol_value  text,
    loaded_value    numeric(18, 8),
    loaded_less_than boolean,
    delta           numeric(18, 8),
    disposition     text        NOT NULL,
    notes           text,
    CONSTRAINT ck_qa_spot_kind CHECK (sample_kind IN ('random_5pct', 'protocol')),
    CONSTRAINT ck_qa_spot_disposition CHECK (
        disposition IN ('match', 'mismatch', 'no_protocol', 'not_in_db', 'unmapped')
    )
);

CREATE INDEX IF NOT EXISTS idx_qa_spot_run
    ON eco.qa_spot_checks (qa_run_id, sample_kind);

COMMENT ON TABLE eco.qa_spot_checks IS
  'Акт выборочной сверки. random_5pct — не менее 5% результатов; protocol — строки PDF.';

-- Присвоить qc_code по правилам текущего прогона. Совпадение с протоколом важнее остальных правил.
CREATE OR REPLACE FUNCTION eco.fn_apply_qc(p_qa_run_id bigint)
RETURNS TABLE (qc_code char(1), n bigint)
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE eco.results r
    SET qc_code = a.code,
        qc_reason = a.reason
    FROM (
        SELECT
            r2.result_id,
            CASE
                WHEN spot.disposition = 'mismatch' THEN 'R'
                WHEN spot.disposition = 'match' THEN 'A'
                WHEN imp.result_id IS NOT NULL THEN 'R'
                WHEN r2.unit IS NOT NULL
                     AND pr.unit IS NOT NULL
                     AND lower(replace(r2.unit, ' ', '')) IS DISTINCT FROM lower(replace(pr.unit, ' ', ''))
                    THEN 'R'
                WHEN outl.result_id IS NOT NULL THEN 'R'
                WHEN r2.less_than THEN 'B'
                ELSE 'C'
            END AS code,
            CASE
                WHEN spot.disposition = 'mismatch' THEN 'protocol_mismatch'
                WHEN spot.disposition = 'match' THEN 'protocol_match'
                WHEN imp.result_id IS NOT NULL THEN 'imputed_nondetect'
                WHEN r2.unit IS NOT NULL
                     AND pr.unit IS NOT NULL
                     AND lower(replace(r2.unit, ' ', '')) IS DISTINCT FROM lower(replace(pr.unit, ' ', ''))
                    THEN 'unit_mismatch'
                WHEN outl.result_id IS NOT NULL THEN 'outlier_10x'
                WHEN r2.less_than THEN 'below_mdl'
                ELSE 'default_accept'
            END AS reason
        FROM eco.results r2
        JOIN eco.parameters pr ON pr.param_id = r2.param_id
        LEFT JOIN (
            SELECT s.result_id,
                   CASE
                       WHEN bool_or(s.disposition = 'mismatch') THEN 'mismatch'
                       WHEN bool_or(s.disposition = 'match') THEN 'match'
                       ELSE NULL
                   END AS disposition
            FROM eco.qa_spot_checks s
            WHERE s.qa_run_id = p_qa_run_id
              AND s.result_id IS NOT NULL
            GROUP BY s.result_id
        ) spot ON spot.result_id = r2.result_id
        LEFT JOIN (
            SELECT DISTINCT r3.result_id
            FROM eco.results r3
            JOIN eco.samples sm ON sm.sample_id = r3.sample_id
            JOIN eco.sampling_events e ON e.event_id = sm.event_id
            JOIN eco.monitoring_points p ON p.point_id = e.point_id
            JOIN eco.staging_lab_import st
                ON st.point_code = p.point_code
               AND st.collection_date = e.event_date
               AND st.processed_at IS NOT NULL
               AND COALESCE(st.extra_json->>'imputed_nondetect', '') = 'true'
               AND eco.fn_resolve_param_id(st.param_code, st.param_name_raw, st.lab_code) = r3.param_id
        ) imp ON imp.result_id = r2.result_id
        LEFT JOIN (
            SELECT DISTINCT r4.result_id
            FROM eco.results r4
            JOIN eco.samples sm ON sm.sample_id = r4.sample_id
            JOIN eco.sampling_events e ON e.event_id = sm.event_id
            JOIN eco.guideline_values gv
                ON gv.param_id = r4.param_id
               AND gv.media_type = e.media_type
               AND e.event_date >= gv.valid_from
               AND (gv.valid_to IS NULL OR e.event_date <= gv.valid_to)
            WHERE NOT r4.less_than
              AND gv.comparison_op IN ('GT', 'GTE')
              AND gv.limit_value > 0
              AND r4.result_value > gv.limit_value * 10
        ) outl ON outl.result_id = r2.result_id
    ) a
    WHERE r.result_id = a.result_id;

    RETURN QUERY
    SELECT r.qc_code, count(*)::bigint
    FROM eco.results r
    GROUP BY r.qc_code
    ORDER BY r.qc_code;
END;
$$;

COMMENT ON FUNCTION eco.fn_apply_qc(bigint) IS
  'Присваивает results.qc_code по правилам qa_rules с учётом сверки прогона p_qa_run_id.';

INSERT INTO eco.schema_migrations (version, description)
VALUES ('009', 'Таблицы QA/QC, причина кода и функция fn_apply_qc')
ON CONFLICT (version) DO NOTHING;
